version: 0.0
os: linux
files:
  - source: SpringBootMavenExample-2.1.1.RELEASE.jar
    destination: /tmp
  - source: fi-proxy
    destination: /tmp
hooks:
  AfterInstall:
    - location: scripts/start_proxy.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 30
      runas: root